feat: Introduce new scene cache management
deep-entertainment/egoventure-example-game pull request #47
Opened 2023-10-14 15:54 UTC by ThmsKnz

BREAKING CHANGE: Adjust cache properties in configuration.tres and generate a cache map before export

Fixes https://github.com/deep-entertainment/issues/issues/38

2023-10-14 16:03 UTC, ThmsKnz commented
Note: The new caching has also been successfully tested by Mikael in his current project.

2023-10-14 21:51 UTC, ThmsKnz commented
I've removed the commented lines you noticed.

2023-11-16 06:55 UTC, dploeger commented
I tested the branch now on mobile as well and on my old iPad the cache goes over the magic marker of 2GB when running down the road left of the house. Is there something to configure for this not to happen or is something wrong?

2023-11-23 06:34 UTC, dploeger requested changes
Such great work! Thanks a lot. Only some smaller comments to fix left.

2023-11-23 06:34 UTC, dploeger commented on addons/egoventure/cache/cache_update_dialog.gd
> +var _scene_list_delta: Array
Please add a doc comment here as well

2023-11-23 06:34 UTC, dploeger commented on addons/egoventure/cache/cache_update_dialog.gd
> +var _cache_map_time_modified
Please add a doc comment here as well

2023-11-23 06:34 UTC, dploeger commented on addons/egoventure/cache/cache_update_dialog.gd
> +#	_scene_list = _read_scene_list(scene_dir)
Please remove commented out code

2023-11-23 06:34 UTC, dploeger commented on addons/egoventure/cache/cache_update_dialog.gd
> +	#Deactivate buttons
```suggestion
	# Deactivate buttons
```

2023-11-23 06:34 UTC, dploeger commented on addons/egoventure/cache/cache_update_dialog.gd
> +	# verbose remains active and can be toggled
```suggestion
	# "verbose" button remains active and can be toggled
```

2023-11-23 06:34 UTC, dploeger commented on addons/egoventure/cache/cache_update_dialog.gd
> +# Start updating the cache map
Add a parameter documentation for the _full parameter. Also, don't use a "\_"-prefix for that parameter

2023-11-23 06:34 UTC, dploeger commented on addons/egoventure/cache/cache_update_dialog.gd
> +#func _read_scene_list(path: String) -> Array:
Remove (or use) this commented out code

2023-11-23 06:34 UTC, dploeger commented on addons/egoventure/cache/cache_update_dialog.gd
> +func _scan_scene(scene_node) -> Array:
Add a doc comment about the parameter and (if possible) denote a type

2023-11-23 06:34 UTC, dploeger commented on addons/egoventure/cache/cache_update_dialog.gd
> +func _get_all_children(node:Node)->Array:
```suggestion
func _get_all_children(node: Node)->Array:
```

2023-11-23 06:34 UTC, dploeger commented on addons/egoventure/cache/scene_cache.gd
> +# Cache map
Better describe what the "Cache map" does or contains

2023-11-23 06:34 UTC, dploeger commented on addons/egoventure/cache/scene_cache.gd
> +# Cache sizes (in kilobyte) - current and maximum
Please split the comment into two above every variable (background is that the API docs are generated from that)

2023-11-23 06:34 UTC, dploeger commented on addons/egoventure/cache/scene_cache.gd
> +	var age: int
Add doc comments on this and the next variable

2023-11-23 06:34 UTC, dploeger commented on addons/egoventure/cache/scene_cache.gd
> +func update_permanent_cache(scene):
If possible, please denote a type for the parameter

2023-11-23 06:34 UTC, dploeger commented on addons/egoventure/cache/scene_cache.gd
> +# - age_remove: all scenes up to this age get removed
Please denote a type for the parameter

2023-11-23 19:59 UTC, ThmsKnz commented
Thanks for the change requests. All have been completed. In addition I removed one log file message that I only added for testing which is not needed in the final version.

2023-11-24 06:38 UTC, dploeger approved these changes
Wondeful. Thanks! 🎁

2023-11-24 06:39 UTC, merged