feat(main_menu): start with save slot page last modified
deep-entertainment/egoventure-example-game pull request #9
Opened 2021-12-12 13:50 UTC by ThmsKnz

This is a small enhancement for user experience when having multiple save games across many save game pages.

The current behavior is that when starting the game always the first save game page is shown containing save games 0 - 11. When a player has multiple save games he/she first needs to flip through the pages to the find the last modified save game.

This enhancement to the main menu sets the initial save slot page to the one containing the latest save game.

2021-12-12 14:17 UTC, ThmsKnz commented
info: I've updated the commit as there were superfluous parantheses in the initial version.

2021-12-13 08:49 UTC, dploeger requested changes
Awesome! Thanks a lot. Just a small remark.

2021-12-13 08:49 UTC, dploeger commented on addons/egoventure/nodes/main_menu.gd
> +var _save_slot_page: int = _get_save_slot_page_last_modified()
I think, this call should be better placed at the end of the `configure` function.

2021-12-13 19:02 UTC, ThmsKnz commented
Thanks for the feedback. Done.

2021-12-13 19:11 UTC, dploeger approved these changes
Great work. Thanks a lot. 🎁

2021-12-13 19:12 UTC, merged

2021-12-13 19:14 UTC, dploeger commented
@ThmsKnz Can you please always merge from develop? I've missed that on this one and accidently merged to main. No problem, just an info.

2021-12-13 19:27 UTC, ThmsKnz commented
@dploeger Sorry about that, I must've accidentally checked out main before the push, will double check next time.